import { TriageReport } from '../types';

export function generateMarkdownReport(report: TriageReport, rawReportSnippet?: string): string {
  const severityEmoji: Record<string, string> = {
    critical: '🔴 CRITICAL',
    high: '🟠 HIGH',
    medium: '🟡 MEDIUM',
    low: '🟢 LOW',
  };

  const severityHeader = severityEmoji[report.severity] || report.severity.toUpperCase();

  const lines: string[] = [
    `# [${severityHeader}] ${report.concise_title}`,
    '',
    `> **Likely Component:** \`${report.likely_component}\``,
    `> **Severity:** **${report.severity.toUpperCase()}**`,
    `> **Triage Model:** ${report.model_used || 'Gemini Flash'}`,
    `> **Generated by:** BugBrief AI`,
    '',
    '---',
    '',
    '## 1. Symptom Summary & Blast Radius',
    report.symptom_summary,
    '',
    '## 2. Reproduction Steps',
    ...report.reproduction_steps.map((step, idx) => `${idx + 1}. ${step}`),
    '',
    '## 3. Plausible Root Causes',
    ...report.likely_causes.map((cause) => `- ${cause}`),
    '',
    '## 4. Actionable Investigation Checklist',
    ...report.investigation_checklist.map(
      (check) => `- [ ] **${check.item}**\n  *Why:* ${check.reason}`
    ),
    '',
    '## 5. Recommended Tests & Verification',
    ...report.recommended_tests.map(
      (test) => `- **[${test.test_type}]** ${test.description}`
    ),
    '',
    '## 6. Questions for Bug Reporter',
    ...report.questions_for_reporter.map((q) => `- ${q}`),
    '',
    '## 7. Alternative Hypothesis & Edge Cases',
    report.alternative_hypothesis,
    '',
  ];

  if (rawReportSnippet) {
    lines.push(
      '---',
      '<details>',
      '<summary>Original Raw Bug Report</summary>',
      '',
      '```text',
      rawReportSnippet.trim(),
      '```',
      '</details>',
      ''
    );
  }

  lines.push('---', '*Triage report automatically synthesized with BugBrief AI.*');

  return lines.join('\n');
}

export function downloadMarkdownFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
